In [2]:
import pandas as pd
import numpy as np

In [8]:
tra_x = pd.read_csv('./train.csv').head(10000)

In [10]:
# handcraft pipeline

    # id 类 certId, dist, bankCard,
    # 时间类  certValidBegin, certValidStop，weekday，setupHour
        - 分箱子
        - 是否周末 weekday
        - 是否白天
    
    # rank类 age, lmt 
        - 严格分箱，弃旧不用；
        
    # 相似类 
        - certId, dist, residentAddr
        - certValidStop, certValidBegin
        - highestEdu, edu
        # DIFF, DIV, SUM, MULTIPLY

In [26]:
tra_x.iloc[:, 90:].head()

,certValidStop,bankCard,ethnic,residentAddr,highestEdu,linkRela,setupHour,weekday,ncloseCreditCard,unpayIndvLoan,unpayOtherLoan,unpayNormalLoan,5yearBadloan,isNew
0,3.952714e+09,-999.0,0,640513,-999,0,9,6,1,0,1,0,0,1
1,4.371149e+09,622848079.0,0,621023,99,11,6,5,1,0,1,0,0,1
2,3.979066e+09,-999.0,0,641204,70,0,1,6,0,0,0,0,0,1
3,4.344538e+09,-999.0,0,-999,-999,-999,13,6,1,0,1,0,0,1
4,3.967834e+09,622700392.0,4,732628,99,11,8,3,1,0,1,0,0,1

In [18]:
tra_x.columns[88:]

Index(['x_78', 'certValidBegin', 'certValidStop', 'bankCard', 'ethnic',
       'residentAddr', 'highestEdu', 'linkRela', 'setupHour', 'weekday',
       'ncloseCreditCard', 'unpayIndvLoan', 'unpayOtherLoan',
       'unpayNormalLoan', '5yearBadloan', 'isNew'],
      dtype='object')

In [9]:
tra_x

,id,certId,loanProduct,gender,age,dist,edu,job,lmt,basicLevel,...,highestEdu,linkRela,setupHour,weekday,ncloseCreditCard,unpayIndvLoan,unpayOtherLoan,unpayNormalLoan,5yearBadloan,isNew
0,1,640582,1,2,27,640500,0,8,5.963,3,...,-999,0,9,6,1,0,1,0,0,1
1,2,621023,2,2,25,640600,0,3,6.467,3,...,99,11,6,5,1,0,1,0,0,1
2,3,641283,1,2,37,641200,70,5,0.596,1,...,70,0,1,6,0,0,0,0,0,1
3,4,340821,3,2,29,340821,0,4,6.300,3,...,-999,-999,13,6,1,0,1,0,0,1
4,5,732628,2,2,22,732628,0,2,6.700,2,...,99,11,8,3,1,0,1,0,0,1
5,6,610221,3,2,27,610221,0,4,5.867,3,...,-999,-999,11,3,1,0,1,1,0,1
6,7,629004,1,1,31,620100,0,3,12.630,1,...,-999,0,17,5,1,1,0,1,0,1
7,8,822223,1,2,32,822223,0,3,1.096,1,...,99,0,14,6,1,1,1,0,0,1
8,9,632503,1,2,27,640700,0,4,0.830,2,...,-999,0,2,6,0,0,1,0,0,1
9,10,722323,2,2,37,722300,0,3,7.667,1,...,-999,12,17,5,0,0,1,0,0,1
10,11,630724,1,2,28,630700,0,2,1.463,1,...,-999,0,0,6,1,0,0,0,0,1
11,12,571326,3,2,19,571326,0,4,2.800,2,...,-999,-999,11,5,0,0,1,0,0,1
12,13,572325,1,2,27,571600,0,3,0.596,3,...,99,0,6,6,1,0,1,0,0,1
13,14,810602,1,2,26,810100,0,3,1.396,3,...,-999,0,13,7,1,0,1,0,0,1
14,15,352625,2,1,27,352620,0,4,0.967,3,...,-999,10,10,5,1,0,1,0,0,1
15,16,530281,2,2,20,530200,0,3,4.467,3,...,99,11,17,1,1,0,1,0,0,1
16,17,733522,2,2,26,730900,70,8,7.033,2,...,70,0,19,4,1,0,1,0,0,1
17,18,432321,1,2,27,410100,0,3,6.296,1,...,-999,0,15,5,1,0,1,1,0,1
18,19,542422,1,2,29,510100,0,8,1.296,1,...,-999,0,0,6,1,1,1,0,0,1
19,20,621126,1,2,25,621126,0,4,6.630,3,...,99,0,17,6,1,0,1,0,0,1
20,21,822824,2,2,22,821000,0,6,6.167,1,...,99,1,20,5,1,0,1,0,0,1
21,22,622201,2,2,38,620900,0,4,4.400,1,...,99,0,18,5,1,0,1,0,0,1
22,23,732322,3,2,24,732322,0,4,1.667,2,...,-999,-999,0,5,1,0,1,0,0,1
23,24,722132,1,2,33,720100,0,3,2.530,1,...,-999,1,6,6,1,0,1,0,0,1
24,25,730321,2,2,24,730100,30,3,5.600,3,...,99,11,14,7,1,0,1,0,0,1
25,26,630623,1,2,20,630600,0,1,3.296,1,...,-999,0,21,5,0,0,1,0,0,1
26,27,621023,2,2,23,621023,0,4,6.133,2,...,99,0,10,5,0,0,1,0,0,1
27,28,640921,2,2,29,640900,0,3,3.600,1,...,-999,1,14,6,0,0,1,0,0,1
28,29,531002,3,2,33,531002,0,3,6.900,1,...,-999,-999,19,1,1,1,1,0,0,1
29,30,571502,1,2,26,571500,0,10,1.163,1,...,-999,1,2,6,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,9971,611423,1,2,31,510100,0,4,7.037,1,...,-999,0,15,3,1,0,1,0,0,1
9971,9972,722322,3,2,22,722322,0,4,1.433,2,...,-999,-999,13,6,1,0,1,0,0,1
9972,9973,510107,2,2,37,530900,0,8,9.333,1,...,99,1,14,5,1,0,1,0,0,1
9973,9974,650322,3,2,45,650320,0,2,2.233,3,...,-999,-999,20,7,1,0,1,1,0,1
9974,9975,520581,1,2,32,520500,0,4,9.963,1,...,-999,1,3,6,1,0,1,1,0,1
9975,9976,611322,1,2,29,310100,0,3,2.563,1,...,-999,0,16,6,1,0,0,0,0,1
9976,9977,610183,3,2,28,610183,0,4,9.700,1,...,-999,-999,13,4,1,1,1,1,0,1
9977,9978,652122,2,2,31,650100,0,3,7.533,1,...,-999,11,0,3,1,0,1,0,0,1
9978,9979,570205,1,1,36,570200,0,4,10.630,1,...,-999,1,4,6,1,0,1,0,0,1
9979,9980,542423,3,2,22,542420,0,5,0.967,2,...,-999,-999,11,7,1,0,1,0,0,1
9980,9981,521322,2,1,26,521300,0,4,8.000,3,...,99,11,6,6,1,0,1,0,0,1
9981,9982,562330,1,2,25,700100,0,5,8.296,1,...,-999,0,22,5,1,0,1,0,0,1
9982,9983,733123,2,1,25,733123,0,3,7.667,1,...,99,1,9,5,1,0,1,0,0,1
9983,9984,420381,1,2,27,510100,0,3,7.963,1,...,-999,0,1,6,1,0,1,0,0,1
9984,9985,722131,1,1,44,720300,0,3,0.830,3,...,-999,1,11,1,1,1,1,0,0,1
9985,9986,710322,3,2,24,710322,0,7,1.600,2,...,-999,-999,18,2,1,0,1,0,0,1
9986,9987,332828,2,2,41,331000,0,3,6.100,3,...,99,11,7,5,0,0,1,0,0,1
9987,9988,640222,2,2,28,640222,0,3,6.900,3,...,99,1,0,3,1,1,1,0,0,1
9988,9989,530724,2,2,21,530724,0,3,1.133,3,...,99,0,17,7,1,0,1,0,0,1
9989,9990,612726,2,2,26,612726,0,3,8.767,2,...,99,10,12,3,1,0,1,0,0,1
9990,9991,570826,2,2,30,570826,0,4,3.333,1,...,-999,1,12,7,1,0,1,0,0,1
9991,9992,722427,2,2,32,722420,0,4,1.667,1,...,-999,10,22,4,-999,-999,-999,-999,1,1
9992,9993,630381,2,1,28,640400,0,3,7.367,1,...,-999,1,9,6,1,0,1,0,0,1
9993,9994,530227,1,2,25,530200,0,6,19.963,1,...,-999,0,23,5,1,0,1,1,0,1
9994,9995,620702,2,2,22,620702,0,4,3.533,2,...,99,0,15,1,1,0,1,0,0,1
9995,9996,330281,3,1,27,330281,0,4,2.300,3,...,-999,-999,16,3,1,0,1,0,0,1
9996,9997,710304,2,2,33,710304,0,1,3.967,1,...,-999,0,19,5,1,1,1,0,0,1
9997,9998,570921,1,2,40,570900,0,3,5.963,3,...,-999,1,4,6,1,1,1,0,0,1
9998,9999,612801,3,2,40,612800,0,4,1.633,2,...,-999,-999,12,4,1,0,1,0,0,1
9999,10000,641881,2,2,32,641800,0,3,3.500,1,...,99,10,16,5,1,0,1,0,0,1